# Simple workflow for deploying static content to GitHub Pages
name: Deploy Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:  write-all


jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: copy to github.io
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "username@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Afig-Asso/Afig-Asso.github.io.git target
          rm -rf target/entreprises/*
          cp -r site/* target/entreprises/
          ls target/entreprises/
          cd target
          git add entreprises/
          git diff-index --quiet HEAD || git commit -am "Automatic publish from github.com/Afig-Asso/entrerprises"
          git push
          
