# Simple workflow for deploying static content to GitHub Pages
name: Deploy Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: copy to github.io
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/Afig-Asso/Afig-Asso.github.io target
          ls
